# Generated by Django 4.1.7 on 2023-03-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0003_remove_event_label_remove_event_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="endTime", new_name="endDate",
        ),
        migrations.RenameField(
            model_name="event", old_name="startTime", new_name="startDate",
        ),
    ]
