# Generated by Django 4.1.7 on 2023-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0004_rename_endtime_event_enddate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="description", new_name="notes",
        ),
        migrations.RemoveField(model_name="event", name="type",),
        migrations.AddField(
            model_name="event", name="allDay", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="rRule",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
