# Generated by Django 4.1.7 on 2023-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0005_rename_description_event_notes_remove_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
