# Generated by Django 4.1.7 on 2023-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0006_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="rRule",
            field=models.CharField(default="", max_length=512),
        ),
    ]
