# Generated by Django 4.1.7 on 2023-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0008_alter_event_rrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="rRule",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
    ]
