# Generated by Django 4.1.7 on 2023-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0009_alter_event_rrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="endDate", field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
