# Generated by Django 4.1.7 on 2023-03-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0010_alter_event_enddate_alter_event_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="endDate", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="event", name="startDate", field=models.CharField(max_length=64),
        ),
    ]
