# Generated by Django 4.1.7 on 2023-03-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0012_alter_event_enddate_alter_event_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="endDate", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event", name="startDate", field=models.DateTimeField(),
        ),
    ]
