# Generated by Django 4.1.7 on 2023-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0016_alter_event_exdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_Msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("message", models.CharField(max_length=2048)),
            ],
        ),
    ]
